# 👇 MUST be first so CocoaPods can find RNWorklets / Reanimated specs
source 'https://cdn.cocoapods.org/'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# RN 0.81.x + Reanimated: use STATIC frameworks
use_frameworks! :linkage => :static

target 'ArabSocialDev' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Absolute path to your app root
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add extra pods here if needed

end

# -------- Global post_install (outside target) --------
post_install do |installer|
  # Standard RN post-install hooks
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )

  # Ensure dSYM is produced for all pods (incl. hermes-engine) in Release
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      next unless config.name == 'Release'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
      config.build_settings['COPY_PHASE_STRIP'] = 'NO'
    end
  end
end
